### ISSUE TITLE
Adaptive Bitrate always dropped to low quality.

### ISSUE THREAD

**Issue by rjtoledo** [ant-media/Ant-Media-Server#3456]
### Short description
After watching the stream for 5-10 minutes the stream suddenly dropped to the lowest quality and it will not switch back to a high-quality stream.  I tried to wait if for another 30 min but I doesn't switch back to high quality it stayed in low quality.
My internet speed is fine too I got around 55 Mbps of download and 80 mbps of upload. 

I tried to switch from another VPS provider still no luck I use Linode for my production environment and AWS for my test environment they both have the same issues.

Linode server = I installed manually the server following the antmedia's guide here wiki

AWS = is using the  Antmedia AWS market place.

They have both OS Versions and settings and the all located in Singapore region.

### Environment

* Operating system and version:  Ubuntu 18.04
* Java version: openjdk 11.0.11 2021-04-20

OpenJDK Runtime Environment (build 11.0.11+9-Ubuntu-0ubuntu2.18.04)
OpenJDK 64-Bit Server VM (build 11.0.11+9-Ubuntu-0ubuntu2.18.04, mixed mode, sharing)
* Ant Media Server version: Enterprise Edition 2.3.3.1 20210609_2033 
* Browser name and version: Google Chrome Version 91.0.4472.164 (Official Build) (64-bit)

Linode Specs 
48 CPU Cores Dedicated
96 GB RAM
1920 GB Storage
Monthly Network Transfer (16000 GB limit)
Region: Singapore

AWS Specs
Region: Singapore
c5.2xlarge

### Steps to reproduce
1. create a custom stream app
2. enable rtmps by editing red5-core.xml
3.use obs/vmix (result same) 
4.encoder settings ( I just follow this guide https://github.com/ant-media/Ant-Media-Server/wiki/RTMP-Publishing )
5. start stream using obs/vmix publishing settings is set to rtmps/ffmpeg2  and i also applied hash token for publishing.
6. after stream is started the first 4 minutes is fine, 5 - 8 min mark it will dropped to low quality and it will never switch back to high quality. must do manual switch to switch higher quality.

### Expected behavior
after switching to low quality the stream should be able to switch back automatically to high quality, it doesn't have the viewer to manually switch its video resolution.  and should be not switching to low quality as the internet bandwidth is enough to stream the video alone.

### Actual behavior
5-8 minute mark it automatically drops to low-quality video resolution even the internet is good enough to play the video stream. and it doesn't switch to high-quality video resolution.

[ant-media-server.log](https://github.com/ant-media/Ant-Media-Server/files/6832538/ant-media-server.log)

 

### Logs
__Place logs on [pastebin](http://pastebin.com/) or elsewhere and put links here__

Video
https://mega.nz/file/0CxHWSya#cPX7mC8P_yS-XQcvc4-GWn4r-wFKSF7f7G0vQUEHCcU

Join [Google Group](https://groups.google.com/forum/#!forum/ant-media-server) and be a part of Ant Media Server Community.

**Comment by mekya** [comment]
Hi @rjmtldo ,

We had similar discussions and tests with you.

 Are you sure that your network between client to server is good enough?

The problem is sometimes on the server network. Not about the client network.

**Comment by rjmtldo** [comment]
Hi @mekya can I send you privately my mtr results there's no packet loss from our cloud server and to our network that's why I'm wondering why this issue occurs? i will send it to slack directly.

**Comment by rjmtldo** [comment]
I think it's never gone to our site, we also use aws this time it has a gigabit network performance.  
![antmedia bandwidth](https://user-images.githubusercontent.com/72129826/127314974-8a7b8081-0e30-4217-91b3-a5d7a079c136.png)
![antmedia mtr](https://user-images.githubusercontent.com/72129826/127315003-a16632de-4345-4443-beef-f99dff917c6e.png)

**Comment by mekya** [comment]
Hi @rjmtldo ,

Thank you for the update. 

When I take a look at the statistics, it seems that packet loss 1330 and jitter is 0.157 sec.

In a good network conditions, packet loss should be 0 and jitter should be less 0.050 sec(50msec). This is why you're having weak network alert. 

It seems there is a bottleneck in somewhere in the internet path between your server and your client. It's likely not under your control. Let's ask this question to the AWS support and keep us updated  I'm also happy to work finding a better explanation/workaround solution for this problem.

**Comment by rjmtldo** [comment]
@mekya  is a cdn will have impact to the viewers side will it help solve this network issues?  we are planning to get those services and boost it on viewers region.

**Comment by mekya** [comment]
Mainly if the instances are close to the viewers then it will have impact to the viewers side. It will help solve this network issue. 

Traditional CDN does not support WebRTC playback. You may need to boost new instances on viewers region or you can use HLS in order to play directly with CDN.

**Comment by rjmtldo** [comment]
Hi, @mekya I see so let me know if this solution will be effective?  We will try to set up AM  multi-level cluster one Origin Server in Singapore Data Center and one Edge Server in Thailand which is closest to my viewers.  note that the publisher will be publishing the streams from Hong Kong Data Center.  Do you think is this a good idea?

**Comment by mekya** [comment]
Yes, it's a good idea. It should perform well. 

Technically, you don't need to have multi-level cluster for this as if it's like that.  
Just create a cluster and let the origin and edge use their global IP by changing `conf/red5.properties`

Change this parameter value from `false` to `true`
```
useGlobalIp=true
```  

Restart the service
```
sudo service antmedia restart
```

**Comment by rjmtldo** [comment]
Thanks, @mekya  btw I know ask this several times but the systems keep on updating if I have 48 core in my origin server does it need to be the same as my edge server?  I have a peak of 700 viewers and 300 viewers on average.  I have two stream apps that use adaptive bitrate  720p 360p and 240p and the other is 480p 360p 240p.

**Comment by mekya** [comment]
Hi @rjmtldo ,

No worries. Origin server and edge server does not need to be in the same spec.  Their size and number of instances can be different according to the number of broadcasts and viewers. 

Regards,
A. Oguz

**Comment by tkdave** [comment]
To get back to original topic on this post, this is the most common issue we have had reported by our users. Internet connection is good for them, but they get knocked down to low stream quality, and it never picks back up. As we investigate, can you point us to some resources on how this detection is implemented? How quickly should it go back to high quality after dropping to lower bitrate stream?

**Comment by mekya** [comment]
Hi @tkdave ,

`Internet connection is good for them` generally does not always mean that the connection is good between server and client to transfer real-time data with high quality. 

Here are the points to check
- Check the jitter, packet lost and rtt time in stats. The stats(packet lost and jitter) are bad in this sample. 
 
<img width="414" alt="Screen Shot 2021-09-30 at 12 57 10" src="https://user-images.githubusercontent.com/3456251/135431199-a1412d32-550e-4be6-b30f-1c0f07b12674.png">

- Server reports the estimated bandwidth for the client and video bitrate, you can also monitor them.  Player shows a message when it detects the connection is not good enough. Check this out -> https://github.com/ant-media/StreamApp/blob/master/src/main/webapp/play.html#L594

- If you think the estimation are wrong, you can force the resolution on the client side as in this sample. 
https://github.com/ant-media/StreamApp/blob/master/src/main/webapp/player.html#L415

<img width="479" alt="Screen Shot 2021-09-30 at 13 02 10" src="https://user-images.githubusercontent.com/3456251/135433959-a2dd483a-6641-4e19-a652-838db4a7228b.png">

**Comment by tkdave** [comment]
In our tests using various network conditioning tools, we can trigger ABR function to drop to low quality, but it always goes from our 1080p down to our low quality 240, skipping over 720 and 480. Once there, it never climbs back up the ABR ladder when network is restored.

If I manually force the 1080p and leave it for a bit, then switch back to "auto", it will stay at 1080p. If I disrupt again, it drops down to 240 again and stays there. 

We have our own player, but I am familiar with your player and your network check and stats. We are collecting all stats now for all clients every 5 seconds, and we have implemented the stream quality picker as well as a display of the current frameHeight. 

We should have more evidence after some events today and tomorrow. We are also working on some automated tests that can reproduce this behavior.

My understanding is that bandwidth estimation and stream selection happens on the server-side. Is this correct?

**Comment by rjmtldo** [comment]
@tkdave you still encountering this issue?  do you get manage to fix it by your self?

**Comment by mekya** [comment]
Hi @tkdave @rjtoledo ,

We have two updates for this problem. We've changed the algorithm to the packet lost and RTT values rather than bandwidth estimation for WebRTC. Because bandwidth estimation is not calculated correctly such as your case. 

We've removed the render limitation in HLS playback so that it plays the highest quality if there is no network bottleneck.

We plan to release 2.6.0 next week that includes these fixes and you can try the 2.6.0 version or you can download latest snapshot and try it on your end. 

Please let me know if it works for you

**Comment by rjtoledo** [comment]
Wow cool thanks for this @mekya

**Comment by mekya** [comment]
My pleasure @rjtoledo . Let me know if it works for you
