### ISSUE TITLE
SRT H265 Streams - Stops and Becomes Unplayable After Long Viewing Session

### ISSUE THREAD

**Issue by timantmedia** [ant-media/Ant-Media-Server#5504]
### Short description
SRT H265 streams are streamed to Ant Media Server and then viewed in a browser. 

If we start viewing the streams for a long playback session, after some point in time the stream goes black, and there is the ability to view the video in the Ant Media Server portal player or directly in our application in the browser. 

The amount of time before this occurs does not appear to be fixed, and is usually measured in hours. The server is not under any significant strain with values at around 30-40%.

Also experienced seeing it stream with the broadcasting status offline yet they are in fact playable and broadcasting.

### Environment

* Operating system and version: Azure VM F8 instance
* Java version: 
* Ant Media Server version: Enterprise Edition 2.6.2
* Browser name and version: 
* VP8 codec with 360p ABR

### Steps to reproduce
1. Select stream for viewing
2. Leave the stream playing for a long period of 8+ hours
3. Stream becomes unplayable and refreshing the browser or using a different machine does not resolve the issue
4. Other streams on Ant Media Server still remain functioning
5. The only known solution for fixing playback is to restart Ant Media Service

Stream is currently being sent to srt://test.antmedia.io:4200?streamid=FD103288/GRzNI6RxfaRx8R1o1692779054559 and is showing as not being able to load. 

### Expected behavior
Should play without issue

### Actual behavior
After a few hours, the stream goes blank, and is not able to play. The only way to resolve is to restart the server. 

 

### Logs
__Place logs on [pastebin](http://pastebin.com/) or elsewhere and put links here__

Ask your questions on [Ant Media Github Discussions](https://github.com/orgs/ant-media/discussions)

**Comment by timantmedia** [comment]
@mekya Customer is looking for alternatives because the issue is a blocker. They are looking to scale AMS to 100+ broadcasters if the issue is resolved.

**Comment by mekya** [comment]
Hi @timantmedia,

As far as I see you've reproduced the problem in our test server. Could you please let us have the logs on the test server and let us know the stream id?

Regards
Oguz

**Comment by timantmedia** [comment]
@mekya also customer test server logs are here https://antmedia.freshdesk.com/a/tickets/106777 for stream id jbp3cP0E9CxfSFDC1693850677302

**Comment by timantmedia** [comment]
I reproduced the SRT stream getting stuck in broadcast state by doing the following:

Running this ffmpeg command

`ffmpeg -re -i example.webm -vcodec libvpx -f mpegts "srt://ant-media-server:4200?streamid=LiveApp/stream9"`

The file exists, but I am trying to send vp8 stream to AMS. The terminal shows it's sending data, but once it's finished, the live stream appears in the web panel as broadcasting but nothing is actually getting live streamed and its stuck in broadcasting state.

**Comment by timantmedia** [comment]
@mekya Just wondering if there was any update I can provide the customer?

**Comment by mekya** [comment]
> @mekya here is the ticket with logs and stream id https://antmedia.freshdesk.com/a/tickets/106818 for stream id GRzNI6RxfaRx8R1o1692779054559

I've analyzed the logs. I see there are some other things in the server as a plugin. For instance, it gives this error 
->
```java.lang.NoClassDefFoundError: Could not initialize class io.antmedia.app.NativeInterface$JNA_RTSP_SERVER```

I also see that there are some crashes which may be related to the plugin as well. I think it's good to understand how the user plays the stream and what other plugins/components are in the server


#### In the perspective of fixing the curent problem,
```
Callback is called hsversion: 5  stream id:  FD103288/GRzNI6RxfaRx8R1o1692779054559
2023-09-03 01:19:45,596 [JavaCPP Thread ID 8477] ERROR i.a.enterprise.srt.SRTAdaptor - Sending stream id in use error for stream:org.bytedeco.javacpp.BytePointer[address=0x7f874affbc20,position=0,limit=0,capacity=0,deallocator=null] scope:FD103288
```
According to the logs above,  It seems that the stream is stucked at broadcasting state and it does not accept the stream  It always returning `streamIdInUse` error as in the logs I think we can fix it easily. This is why user don't play it. 
Additionally, It will be very helpful if we know the older logs to understand how the stream stucks at the broadcasting state to confirm the solution we provide is permanent.

**Comment by mekya** [comment]
> I reproduced the SRT stream getting stuck in broadcast state by doing the following:
> 
> Running this ffmpeg command
> 
> `ffmpeg -re -i example.webm -vcodec libvpx -f mpegts "srt://ant-media-server:4200?streamid=LiveApp/stream9"`
> 
> The file exists, but I am trying to send vp8 stream to AMS. The terminal shows it's sending data, but once it's finished, the live stream appears in the web panel as broadcasting but nothing is actually getting live streamed and its stuck in broadcasting state.

I think VP8 is not compatible for mpegts. No matter, server should not behave like this. Let me check.

**Comment by timantmedia** [comment]
@mekya So he is using a Makito Encoder and it is live camera content. Do you need an exact model? Or other details? It's sending SRT H265. 

I can ask if he has older logs, but these we generated from the support page of the web panel. So does that only send a portion of logs from the server? 

I'll ask if he is using any Ant Media Server plugins or do you mean some server plugins or something else?

**Comment by mekya** [comment]
Currently, I've reproduced some scenarios in the logs and implemented the fixes and test codes. It's running in CI right now. 

The issue below is fixed. 
```
Callback is called hsversion: 5  stream id:  FD103288/GRzNI6RxfaRx8R1o1692779054559
2023-09-03 01:19:45,596 [JavaCPP Thread ID 8477] ERROR i.a.enterprise.srt.SRTAdaptor - Sending stream id in use error for stream:org.bytedeco.javacpp.BytePointer[address=0x7f874affbc20,position=0,limit=0,capacity=0,deallocator=null] scope:FD103288
```
 
The problem you mentioned is fixed. I mean vp8 is not compatible with mpegts and we stop the ingestion after it's timeout. So that it does not enter the blocking state
> I reproduced the SRT stream getting stuck in broadcast state by doing the following:
> 
> Running this ffmpeg command
> 
> `ffmpeg -re -i example.webm -vcodec libvpx -f mpegts "srt://ant-media-server:4200?streamid=LiveApp/stream9"`

After CI passes and snapshot is ready on website, we can deliver the user to confirm if it's working for them.

Happy Sunday Coding :) 
Cheers

**Comment by timantmedia** [comment]
@mekya there was a snapshot version generated this morning. I assume this contains the fixes?

**Comment by mekya** [comment]
> @mekya there was a snapshot version generated this morning. I assume this contains the fixes?

Yes

**Comment by timantmedia** [comment]
@mekya The fix did not resolve the customer's issue. The issue is still present, the video says broadcasting, and the encoder is still outputting data, but the video is unplayable, despite using the latest snapshot version.

**Comment by mekya** [comment]
Then we need to get the logs again from the ant media server and streamId that they encounter this problem.

**Comment by timantmedia** [comment]
@mekya The customer is not responding to confirm which stream id is showing the issue, however, this is a list of the stream IDs I found in the log. 

z99sXMsjIf4npeot1696355403015 
Q4n7GppBJ4wz7AHC1696352601320 
78QlHP1D1iaLyKxF1696352615354 
vcISTmzOaEd6vre21696352610835 
2MkpBJqJUpNhVSxK1696352622571

In case it's possible to check the logs on just these few streams to find anything unusual. I asked the customer to comment on this issue.

**Comment by timantmedia** [comment]
Taken out of last sprint, can it be scheduled for this week @mekya

**Comment by mekya** [comment]
Hi @timantmedia 
If there is some space to get some new issues, yes we can schedule it again. 

Regards
Oguz

**Comment by jantekb** [comment]
Closed due to no activity
